### ISSUE TITLE
Errors links pixiv invalid

### ISSUE THREAD

**Issue by socamporomani** [doujinshi-info/frontend-nuxt#11]
![image](https://user-images.githubusercontent.com/43774853/166290156-b54c1fa9-afb9-4031-8ed4-7d38b02f16c4.png)
the response of add pixiv  link
![image](https://user-images.githubusercontent.com/43774853/166290196-548b3b55-b380-41b1-b533-bd5f0e81967b.png)

**Comment by CrimsonSkadi** [comment]
The only way to currently enter the pixiv link is to use the old format "https://pixiv.net/member.php?id=" it doesn't accept the new version.
